version: '3'

volumes:
  data:

services:
  db:
    restart: always
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - $HOME/docker/volumes/postgres/data:/var/lib/postgresql/data
#      - /Library/PostgreSQL/11/data:/var/lib/postgresql/data
#      - data:/var/lib/postgresql/data
#      - ~/docker:/TeamVerwaltung_Docker
    container_name: SpringMvcDemo-postgres-container
  web:
    restart: always
    image: stratilat19/spring-mvc-demo:1.0-SNAPSHOT
#    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - db
    links:
      - db
    container_name: SpringMvcDemo-web-container